### PR TITLE
pref: 让git相关连续尝试工具的通知显示具体仓库

### PR DESCRIPTION
**Pull request by Luna-Grace**
Fix DuckDuckStudio/Fufu_Dev_Tools#7

### CODE REVIEW

**Comment by DuckDuckStudio** [comment]
@fjwxzde run test

**Review by fjwxzde — CHANGES_REQUESTED** [review]
不必要的库
```python
import sys
```

**Comment by DuckDuckStudio** [comment]
@fjwxzde run test

**Review by fjwxzde — COMMENTED** [review]
@DuckDuckStudio 
需要手动审查
原因：
可能有意外修改
- https://github.com/DuckDuckStudio/Fufu_Tools/pull/93/files#diff-3da8d478ffeb2c8e6eb8df6d29896e2eb71b9184229518b6aedadcea35de9f81
- https://github.com/DuckDuckStudio/Fufu_Tools/pull/93/files#diff-6f65c2c4d13f52892c0651219702dbfcec14e679b979693cd91fc86a1366a3f3
- https://github.com/DuckDuckStudio/Fufu_Tools/pull/93/files#diff-7544dbba656150e987476771f9cc1c6534445d0d5bd13d92f197d6723f30f2de

**Review by DuckDuckStudio — DISMISSED** [review]

**Comment by DuckDuckStudio** [comment]
@fjwxzde approve

**Review by DuckDuckStudio — APPROVED** [review]

**Comment by fjwxzde** [comment]
@DuckDuckStudio 
合并被阻止
```
Merging can be performed automatically with 2 approving reviews.
```

**Review by DuckDuckStudio — APPROVED** [review]

**Comment by DuckDuckStudio** [comment]
@Luna-Grace 
重开一个拉取请求吧...

**Pull request closed without merging**
